backend:
  name: git-gateway
  branch: master

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Index Page"
        name: "index"
        file: "index.html"
        fields:
          - { label: "Contenido", name: "body", widget: "markdown" }
